[UI] storybookでサインイン、サインアップ用のコンポーネント作成
yurihoka/Beyond pull request #13
Opened 2024-10-28 19:51 UTC by yurihoka

## 📝 概要
storybookでサインイン、サインアップ用のコンポーネント作成

## 🧐 なぜこの変更をするのか
サインイン、サインアップ用コンポーネントが正しく表示されるか確認するため

### 影響のある Issue
なし
Closes #

### 参照する Issue や PR
#2 

## 💪 やったこと
- Buttonコンポーネントの作成
- Inputコンポーネントの作成
- Formコンポーネントの作成 (Button+Input)

### スクリーンショット/動画/gif など
なし

### テスト

- [ ] あり
- [ ] なし(必要なし)
- [ ] なし(ヘルプが必要)

## 💬 課題

### 悩んでいること
- ButtonコンポーネントとFormコンポーネントで使用するPropsが同じため、まとめるべきかどうか

### とくにレビューしてほしいところ
- コードが重複していないか（まとめられる箇所があればコメントください！）

## その他

2024-10-31 04:05 UTC, HidemichiShimura requested changes

2024-10-31 04:05 UTC, HidemichiShimura commented on src/components/common/Button.tsx
> +const Button = ({ variant }: Props) => {
```suggestion
const Button = ({ entry }: Props) => {
```
`variant`は抽象的すぎてどのコンポーネントのpropsにも当てはまる気がするのでentryとかの方がより具体的で分かりやすいかもです

2024-10-31 04:05 UTC, HidemichiShimura commented on src/components/common/Button.tsx
> +};
common配下に`types.d.ts`を作って、そこにこのタイプを移行してもいいです。そこからタイプimportして使い回す感じで

2024-10-31 04:05 UTC, HidemichiShimura commented on src/components/common/Button.tsx
> +};
propsは`signin` `signup`の方がコンポーネント呼び出し側としては使いやすい気がするんですがどうでしょうか

2024-11-03 01:27 UTC, yurihoka commented
@HidemichiShimura 
レビューありがとうございました！お手隙で確認お願いします！

2024-11-03 22:35 UTC, HidemichiShimura requested changes

2024-11-03 22:35 UTC, HidemichiShimura commented on src/components/common/Button.stories.ts
> +        component: "ボタンコンポーネント",
```suggestion
        component: "ログイン/サインアップフォーム用ボタン",
```
ここにはコンポーネントの具体的な概要を書いた方が良いと思うので、こんな感じの方がベターかもです

2024-11-03 22:35 UTC, HidemichiShimura commented on src/components/common/Form.stories.ts
> +        component: "サインイン、サインアップコンポーネント",
```suggestion
        component: "サインイン、サインアップフォーム",
```
コンポーネントであることは明らかなので省略して大丈夫です👍

2024-11-03 22:35 UTC, HidemichiShimura commented on src/components/common/Input.stories.ts
> +        component: "インプットコンポーネント",
```suggestion
        component: "ログイン/サインアップフォームのEmail/Password用インプット",
```

2024-11-04 02:25 UTC, yurihoka commented
@HidemichiShimura 
ありがとうございます！修正したので再度確認お願いします。

2024-11-04 02:31 UTC, HidemichiShimura approved these changes
大丈夫です！対応ありがとうございます！

2024-11-04 02:33 UTC, merged