nav barコンポーネント作成
yurihoka/Beyond pull request #16
Opened 2024-11-04 04:53 UTC by yurihoka

## 📝 概要
ナビゲーションバーコンポーネントの作成

## 🧐 なぜこの変更をするのか
ダッシュボードにナビゲーションバーを表示させたいから

### 影響のある Issue
なし

### 参照する Issue や PR
#15 

## 💪 やったこと

- ナビゲーションバーの作成
- ナビゲーションバーにHOMEとユーザーのメールアドレス表示

### テスト

- [ ] あり
- [ ] なし(必要なし)
- [ ] なし(ヘルプが必要)

## 💬 課題
なし

### 悩んでいること

### とくにレビューしてほしいところ

## その他

2024-11-06 01:19 UTC, HidemichiShimura requested changes
対応素早くて助かります！ちょっと修正かけたので確認お願いします！

2024-11-06 01:19 UTC, HidemichiShimura commented on src/components/common/Navbar.tsx
> +export type UserEmailType = {
```suggestion
export type NavbarProps = {
```
Propsのtype名は`<Component name>Props`に統一しましょう！

2024-11-06 21:32 UTC, yurihoka commented on src/components/common/Navbar.tsx
> +export type UserEmailType = {
@HidemichiShimura 
確認ありがとうございます！
Button（`type.d.ts`）や`Input.tsx`のpropsのtype名は`<Component name>Type`になってますが、そのままでも問題ないですか？
そのままでもいい場合、変更しなくても大丈夫な理由を教えてもらえると助かります！

2024-11-08 23:01 UTC, HidemichiShimura commented on src/components/common/Navbar.tsx
> +export type UserEmailType = {
@yurihoka 
そこも`<Component name>Props`に統一した方がいいですね！
対応お願いします

2024-11-08 23:24 UTC, yurihoka commented
@HidemichiShimura 
一旦NavbarのPropsのType名だけ変更したので、確認お願いします！
他のPropsのType名は別Issueで対応します！

2024-11-08 23:24 UTC, yurihoka commented on src/components/common/Navbar.tsx
> +export type UserEmailType = {
@HidemichiShimura 
一旦NavbarのPropsのType名だけ変更したので、確認お願いします！
他のPropsのType名は別Issueで対応します！

2024-11-09 00:48 UTC, HidemichiShimura approved these changes

2024-11-09 00:48 UTC, merged