feat: ダッシュボード用のstart workoutボタン追加
yurihoka/Beyond pull request #19
Opened 2024-11-04 05:51 UTC by yurihoka

## 📝 概要
- ダッシュボード用のstart workoutボタン追加

## 🧐 なぜこの変更をするのか
- ダッシュボードにstart workoutボタンを表示させたいから

### 影響のある Issue
#18 
Closes #

### 参照する Issue や PR
#15
#17 

## 💪 やったこと

- Buttonコンポーネントにstart workoutを追加

### スクリーンショット/動画/gif など

### テスト

- [ ] あり
- [ ] なし(必要なし)
- [ ] なし(ヘルプが必要)

## 💬 課題

### 悩んでいること

### とくにレビューしてほしいところ

## その他

2024-11-06 01:29 UTC, HidemichiShimura requested changes
修正お願いします！

2024-11-06 01:29 UTC, HidemichiShimura commented on src/components/common/Button.stories.ts
parameterのコンポーネントdescriptionも合わせて修正お願いします！

2024-11-06 21:27 UTC, yurihoka commented on src/components/common/Button.stories.ts
@HidemichiShimura 
修正したので確認お願いします！

2024-11-08 23:02 UTC, HidemichiShimura approved these changes

2024-11-09 00:28 UTC, merged