[UI] サインイン、サインアップ画面のUI作成
yurihoka/Beyond pull request #67
Opened 2024-12-07 06:18 UTC by yurihoka

## 📝 概要
サインイン、サインアップ画面のUI作成

## 🧐 なぜこの変更をするのか
サインイン、サインアップ画面のpageファイルを作成するため

### 影響のある Issue

Closes #

### 参照する Issue や PR

## 💪 やったこと

- InputとボタンコンポーネントをPageファイルにインポート

### スクリーンショット/動画/gif など

### テスト

- [ ] あり
- [ ] なし(必要なし)
- [ ] なし(ヘルプが必要)

## 💬 課題

### 悩んでいること

### とくにレビューしてほしいところ

## その他

2025-01-16 12:11 UTC, HidemichiShimura reviewed
`src/app`配下に`signup``signin`のディレクトリを切って、各ディレクトリにページコンポーネントを配置するようにお願いします。`/api`はAPI用のディレクトリなので 👍🏻 

Nextのディレクトリ構造などはここを見てみるといいかもですよ
[How to create layouts and pages](https://nextjs.org/docs/app/getting-started/layouts-and-pages)

2025-01-16 12:11 UTC, HidemichiShimura commented on src/app/api/login/page.tsx
> +const Page: NextPage<ButtonProps> = ({ entry }) => {
```suggestion
const Page: NextPage = () => {
```
ページコンポーネント自体はpropsを取らないので削除して大丈夫です。

Signup/Singinのフォーム切り替えはページに渡すpropsではなく、アクセスされるパス`/signup`, `/signin`それぞれのページコンポーネント内でそれぞれのFormコンポーネントに渡すようにするイメージです。

2025-01-18 11:36 UTC, yurihoka commented on src/app/api/login/page.tsx
> +const Page: NextPage<ButtonProps> = ({ entry }) => {
コンポーネントの親子関係を正しく把握していませんでした！指摘ありがとうございます！

2025-01-18 13:28 UTC, HidemichiShimura requested changes
このissueはサインアップ画面のUI作成も含んでいるので、追加でそこの対応もお願いします🙇

2025-01-18 13:28 UTC, HidemichiShimura commented on src/app/signin/page.stories.ts
> +        component: "サインイン/サインアップ画面",
```suggestion
        component: "サインイン画面",
```
サインアップページは別で作るはずはので、ここはサインイン画面のみでお願いします

2025-01-18 13:28 UTC, HidemichiShimura commented on src/app/signin/page.stories.ts
> +  },
`<Page />`はpropsを取らないのでここは不要です

2025-01-18 13:28 UTC, HidemichiShimura commented on src/app/signin/page.stories.ts
> +  },
上と同じ理由で不要です

2025-01-19 06:43 UTC, HidemichiShimura approved these changes

2025-01-19 06:43 UTC, HidemichiShimura approved these changes

2025-01-19 06:44 UTC, merged